version: '3'
services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build:
      context: .
    command: sh -c "rm -rf /usr/src/app/tmp/pids/server.pid;
      bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - db

  redis:
    image: redis:5-alpine
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/usr/src/app
      - bundle_cache:/usr/local/bundle
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  bundle_cache:
  redis:
  postgres:
